name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Enable Corepack
      run: corepack enable

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Node.js dependencies
      run: yarn install

    - name: Archive
      run: |
        yarn archive

    - name: Move archive files
      run: |
        mkdir -p temp_folder
        mv build/test-external-widget.zip ./temp_files
        rm -rf build
